import { Launch } from "@/types/launchType";
import Head from "next/head";
import { useState } from "react";
import { getLaunches } from "./api/_service";

export default function Home() {
  const [launches, setLaunches] = useState<Launch[]>([]);
  const handleLaunches = () => {
    getLaunches().then((res) => {
      setLaunches(res);
      console.log(res);
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Next Space Launch</h1>
      <button onClick={handleLaunches}>test</button>
      <ul>
        {launches.map((launch) => (
          <li key={launch.id}>
            <p>{launch.id}</p>
            <p>{launch.name}</p>
            <p>{launch.launch_description}</p>
            <p>{launch.slug}</p>
          </li>
        ))}
      </ul>
    </>
  );
}
